name: Build and publish apt repo

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Rebuild data and package
      working-directory: scraper
      run: |
        echo "PWD=$(pwd)"
        echo "Listing current directory:"
        ls -la
        echo "Listing parent (repo root):"
        ls -la ..
        echo "Listing ../data:"
        ls -la ../data | head -20 || echo "No ../data"
        chmod +x build_deb.sh make_apt_repo.sh sign_release.sh || true
        echo "Running build_deb.sh..."
        ./build_deb.sh "$(pwd)/../data" || { echo "build_deb.sh failed with exit code $?"; exit 1; }
        # ensure .deb exists
        echo ".deb file:"
        ls -l fortune-swahili_0.1_all.deb || { echo "ERROR: .deb not found"; exit 1; }

    - name: Create apt repo
      working-directory: scraper
      run: |
        ./make_apt_repo.sh ./fortune-swahili_0.1_all.deb ./apt-repo

    - name: Import GPG key (from secret) and sign Release
      continue-on-error: true
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: |
        set +e  # don't exit on error, we want to see all diagnostic output
        if [ -z "$GPG_PRIVATE_KEY" ]; then
          echo "::warning::No GPG_PRIVATE_KEY secret provided; skipping signing"
          exit 0
        fi
        # import key into an isolated GNUPGHOME so we don't touch runner keyring
        export GNUPGHOME="$(pwd)/.gnupg-temp"
        rm -rf "$GNUPGHOME"
        mkdir -m700 -p "$GNUPGHOME"
        echo "GNUPGHOME=$GNUPGHOME"
        echo "Importing private key into isolated GNUPGHOME..."
        echo "$GPG_PRIVATE_KEY" | gpg --batch --homedir "$GNUPGHOME" --import 2>&1 | head -20
        IMPORT_STATUS=$?
        echo "GPG import exit code: $IMPORT_STATUS"
        echo "gpg version:" && gpg --version | head -3
        echo "Listing secret keys (homedir):"
        gpg --homedir "$GNUPGHOME" --list-secret-keys --keyid-format LONG 2>&1 || echo "No secret keys found"
        echo "Contents of GNUPGHOME:"
        ls -la "$GNUPGHOME" 2>&1 || true
        # enable loopback pinentry by setting gpg options when invoking sign script
        cd scraper
        echo "Running sign_release.sh..."
        if ./sign_release.sh ./apt-repo/Release "$GPG_PASSPHRASE" 2>&1 | tee sign-output.log; then
          echo "::notice::Sign succeeded"
        else
          echo "::warning::Sign failed, publishing unsigned repo. See sign-output.log below:"
          cat sign-output.log 2>&1 || true
        fi
        echo "Final apt-repo contents:"
        ls -l ./apt-repo 2>&1 || true
        # clean up GNUPGHOME
        rm -rf "$GNUPGHOME" 2>&1 || true

    - name: Publish to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./scraper/apt-repo
        destination_dir: /

